version: '3'
services:
  edge_node_1:
    build: .
    environment:
      - EDGE_NODE_WALLET_PRIVATE_KEY=0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80
    ports:
      - "5001:5000"  # Mapping to different ports for each edge node

  edge_node_2:
    build: .
    environment:
      - EDGE_NODE_WALLET_PRIVATE_KEY=0x59c6995e998f97a5a0044966f0945389dc9e86dae88c7a8412f4603b6b78690d
    ports:
      - "5002:5000"  # Mapping to different ports for each edge node

  edge_node_3:
    build: .
    environment:
      - EDGE_NODE_WALLET_PRIVATE_KEY=0x5de4111afa1a4b94908f83103eb1f1706367c2e68ca870fc3fb9a804cdab365a
    ports:
      - "5003:5000"  # Mapping to different ports for each edge node
