version: '3'
services:
  edge_node_1:
    build: .
    env_file:
      - .env
    environment:
      - EDGE_NODE_WALLET_PRIVATE_KEY=${DOCKER_WALLET_ONE}
    ports:
      - "5001:5000"  # Mapping to different ports for each edge node

  edge_node_2:
    build: .
    env_file:
      - .env
    environment:
      - EDGE_NODE_WALLET_PRIVATE_KEY=${DOCKER_WALLET_TWO}
    ports:
      - "5002:5000"  # Mapping to different ports for each edge node

  edge_node_3:
    build: .
    env_file:
      - .env
    environment:
      - EDGE_NODE_WALLET_PRIVATE_KEY=${DOCKER_WALLET_THREE}
    ports:
      - "5003:5000"  # Mapping to different ports for each edge node
